name: Weather ETL

on:
  push:
    branches: [ main ]

  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  etl-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install requests

      - name: Run ETL
        run: python etl.py

      - name: Upload weather forecast
        uses: actions/upload-artifact@v4
        with:
          name: weather-forecast
          path: weather_forecast.csv     
